name: weekly Top 50 CRON
    
on:
  schedule:
    - cron: "*/15 * * * *" #runs at 00:00 UTC every Monday -> every 15th minute

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8 #install the python needed
      - name: install dependencies # install dependencies for py file run
        run: |
          pip install -r requirements.txt
      - name: execute py script # run the run.py to get the latest data
        run: |
          python avg_album_length_playlist.py
        env:
          SPOTIPY_CLIENT_ID:   ${{ secrets.SPOTIPY_CLIENT_ID }}
          SPOTIPY_CLIENT_SECRET: ${{ secrets.SPOTIPY_CLIENT_SECRET }}
          SPOTIPY_REDIRECT_URI:    ${{ secrets.SPOTIPY_REDIRECT_URI }}                       # if run.py requires passwords..etc, set it as secrets
